Tree related questions added in DSA Section
AkashSingh3031/The-Complete-FAANG-Preparation pull request #128
Opened 2021-07-14 19:54 UTC by tanwi1234

2021-07-15 03:06 UTC, AkashSingh3031 requested changes
put extensions of code in place of  `.txt` and also put the number in front of the code
like if code in c++ then codes name `_01)_Diameter_of_tree.cpp`

2021-07-15 07:19 UTC, AkashSingh3031 requested changes
if this code solution on any competitive site then put code `Competitive Programming` folder
otherwise, write full running code with the header file

like this [code](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/tree/master/1%5D.%20DSA/1%5D.%20Data%20Structures/01%5D.%20Array/C%2B%2B) for

2021-07-15 11:30 UTC, janette747 approved these changes

2021-07-17 05:55 UTC, AkashSingh3031 requested changes
Check this
![image](https://user-images.githubusercontent.com/60146338/126027183-33b53d24-99d6-4767-a903-3347fdcb8054.png)

If questions are from GFG then put the question in the proper folder & the proper number wise

For questions click on the blue link
![image](https://user-images.githubusercontent.com/60146338/126027270-a2332021-00df-43f7-b210-c3f96f2394b7.png)

Your folder creation
![image](https://user-images.githubusercontent.com/60146338/126027294-bffd4af4-cfd8-4878-a75a-3e9eba0678f5.png)

---

See this folder creation and numbering
![image](https://user-images.githubusercontent.com/60146338/126027389-6a3a7a9b-6670-484f-98a0-0be86da445b5.png)

Proper folder creation because easy to find the question

2021-07-19 04:13 UTC, closed without merging