Added Code Monk Series and competitive contest code
AkashSingh3031/The-Complete-FAANG-Preparation pull request #138
Opened 2021-07-23 17:28 UTC by RahulSurana123

# Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?
- [ ] YES
- [ ] NO

## Project URL
- 

## What is the current behavior?
- Issue Number: #...

## Category
- [ ] 𝑨𝑺𝑲 𝒀𝒐𝒖𝒓 𝑫𝒐𝒖𝒃𝒕𝒔
- [ ] 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇.
- [ ] 𝑫𝑺𝑨
- [ ] 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
- [ ] 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
- [ ] 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏
- [ ] 𝑷𝒓𝒐𝒋𝒆𝒄𝒕𝒔
- [ ] 𝑰𝒎𝒑𝒐𝒓𝒕𝒂𝒏𝒕 𝑩𝒐𝒐𝒌𝒔 𝒂𝒏𝒅 𝑹𝒆𝒔𝒐𝒖𝒓𝒄𝒆𝒔
- [ ] 𝑩𝒆𝒉𝒂𝒗𝒊𝒐𝒖𝒓𝒂𝒍 𝑰𝒏𝒕𝒆𝒓𝒗𝒊𝒆𝒘 𝑸𝒖𝒆𝒔𝒕𝒊𝒐𝒏𝒔

## Changes
- Description of changes

## **Screenshots** 
- (Add Runnig Work Demo Image)

## Checklist
- [ ] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ ] I've add work in proper folder
- [ ] I've not delete/modify previous codes.

2021-07-23 17:29 UTC, RahulSurana123 commented
Added Code Monk Series and Competitve Contest Codes

2021-07-23 18:56 UTC, AkashSingh3031 requested changes
check code again
attach accepted code screenshot in PR Template

Also, do proper numbering and make folder 

![image](https://user-images.githubusercontent.com/60146338/126828388-e1938814-8c1c-4904-a031-854ac09bae54.png)

see the image and make folders like `.../ 1]. Practice/5]. Code Monk/01]. Arrays & Strings/03). Cyclic shift.cpp `

2021-07-24 05:02 UTC, AkashSingh3031 commented on 3]. Competitive Programming/06]. CodeChef/2]. Compete/2]. Cook-off/Div 3/The Wave.cpp
> +
Accepted
But Add month
like `.../Div 3/June/3). The_Wave.cpp`

2021-07-24 05:53 UTC, RahulSurana123 commented on 3]. Competitive Programming/06]. CodeChef/2]. Compete/2]. Cook-off/Div 3/The Wave.cpp
> +
Done

2021-07-24 07:14 UTC, AkashSingh3031 commented on 3]. Competitive Programming/05]. HackerEarth/1]. Practice/5]. Code Monk Series/1] Arrays & Strings/Cyclic shift.cpp
> +#include <bits/stdc++.h>
check this code again
![image](https://user-images.githubusercontent.com/60146338/126860732-0c9f2620-5593-4758-a170-bfe49bba909b.png)

2021-07-24 10:01 UTC, AkashSingh3031 commented on 3]. Competitive Programming/05]. HackerEarth/1]. Practice/5]. Code Monk Series/5] Number Theory Part 1/Monk and Divisor Conundrum.cpp
> +*/
check this 

no code

2021-07-24 14:31 UTC, AkashSingh3031 reviewed
Accepted

2021-07-24 14:31 UTC, merged