ADDED CODECHEF JUNE LONG CHALLNEGE DIV 3 SOLUTION IN C++
AkashSingh3031/The-Complete-FAANG-Preparation pull request #20
Opened 2021-06-16 17:13 UTC by codeaholic-shub

Hello @AkashSingh3031 ,
Kindly Review this PR !

2021-06-16 17:35 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/MINIMUM_DUAL_AREA.cpp
> +#include<bits/stdc++.h>
Accepted

2021-06-16 17:36 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/MINIMUM_SUBTREE_COVER.cpp
> +#include <bits/stdc++.h>
Accepted

2021-06-16 17:37 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/SUMMER_HEAT.cpp
> +#include<bits/stdc++.h>
Accepted

2021-06-16 17:41 UTC, AkashSingh3031 requested changes
Please check your solution of the 3 problems `Bella ciao`, `Bitwise Tuples`, `Shortest Route`

2021-06-16 17:42 UTC, AkashSingh3031 commented
@codeaholic-shub 
After changing the code again send a Pull Request

2021-06-16 17:44 UTC, codeaholic-shub commented
> Please check your solution of the 3 problems `Bella ciao`, `Bitwise Tuples`, `Shortest Route`

I have already checked , its already submitted solutions of codechef from my account

2021-06-16 21:27 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/BITWISE_TUPLES.cpp
> +#include<bits/stdc++.h>
Accepted

2021-06-16 21:33 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/BELLA_CIAO.cpp
> +#include<bits/stdc++.h>
![image](https://user-images.githubusercontent.com/60146338/122296885-90c61f00-cf18-11eb-8c1f-d5e0a9b00f47.png)

check again

2021-06-16 21:33 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/SHORTEST_ROUTE.cpp
> +
![image](https://user-images.githubusercontent.com/60146338/122296620-3f1d9480-cf18-11eb-9840-7e2851039b31.png)

Check again

2021-06-17 03:40 UTC, codeaholic-shub commented
Hello @AkashSingh3031 ,
I have changed the solution and its correct,
U may check my PR !

2021-06-17 04:50 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/BELLA_CIAO.cpp
> +#include <bits/stdc++.h>
Accepted

2021-06-17 04:51 UTC, AkashSingh3031 commented on 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/SHORTEST_ROUTE.cpp
> +#include <bits/stdc++.h>
Accepted

2021-06-17 04:51 UTC, AkashSingh3031 reviewed
All Accepted

2021-06-17 04:52 UTC, merged