web projects
AkashSingh3031/The-Complete-FAANG-Preparation pull request #353
Opened 2023-05-02 11:00 UTC by prashik2002

# Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?
- [✅ ] YES
- [ ] NO

## Project URL
- []()

## What is the current behavior?
- Issue Number: #... No issues

## Category
- [ ] 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇.
- [ ] 𝑫𝑺𝑨 + CP
- [ ] 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
- [ ] 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏
- [✅ ] 𝑷𝒓𝒐𝒋𝒆𝒄𝒕𝒔
- [ ] 𝑰𝒎𝒑𝒐𝒓𝒕𝒂𝒏𝒕 𝑩𝒐𝒐𝒌𝒔 𝒂𝒏𝒅 𝑹𝒆𝒔𝒐𝒖𝒓𝒄𝒆𝒔
- [ ] 𝑩𝒆𝒉𝒂𝒗𝒊𝒐𝒖𝒓𝒂𝒍 𝑰𝒏𝒕𝒆𝒓𝒗𝒊𝒆𝒘 𝑸𝒖𝒆𝒔𝒕𝒊𝒐𝒏𝒔

## Changes
- Description of changes

## **Screenshots** 
- (Add Running Work Demo Image)
-
# React Blog Project 
![image](https://user-images.githubusercontent.com/88095936/235647275-27e7ee1a-3400-477a-8a1e-fcb4c86e1f40.png)
![image](https://user-images.githubusercontent.com/88095936/235647351-ba983756-8639-4929-a192-a854c63094d6.png)
![image](https://user-images.githubusercontent.com/88095936/235647503-238c1772-b237-4373-9638-921e5901f407.png)

# MERN project
![image](https://user-images.githubusercontent.com/88095936/235648256-4947de71-71fd-4b30-8467-7f211b82d990.png)
![image](https://user-images.githubusercontent.com/88095936/235648406-fc670e1c-2923-4686-921a-dfbe19e00e8e.png)
![image](https://user-images.githubusercontent.com/88095936/235648575-6b859a97-1efd-41df-8103-d928b5c6c05f.png)

## Checklist ✅
- [ ✅] I've read the instructions on the README file before submitting my application.
- [✅ ] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [✅] I've checked the issue list before deciding what to submit.
- [ ✅] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ ✅] I've add work in proper folder
- [ ✅] I've not delete/modify previous codes.

2023-05-02 17:42 UTC, AkashSingh3031 commented
You delete the many files 

Don't remove any file
If any issue in the file so, create an issue

2023-05-03 00:49 UTC, prashik2002 commented
I have deleted the node_modules folder nothing else

2023-05-03 09:25 UTC, AkashSingh3031 commented
> I have deleted the node_modules folder nothing else

Check-in file change section
You change a total of 163 files
In these files, many files are deleted

Check the above comment code where I maintain ***Restore***
These files are deleted

2023-05-03 09:26 UTC, AkashSingh3031 requested changes

2023-05-03 11:54 UTC, closed without merging