Added 5 Programs using C++
AkashSingh3031/The-Complete-FAANG-Preparation pull request #59
Opened 2021-06-20 20:44 UTC by RAUNAK-PANDEY

2021-06-20 22:22 UTC, AkashSingh3031 requested changes
Can you check your PRs 
Because, all code already president in this repository

2021-06-20 22:27 UTC, AkashSingh3031 requested changes
Can you check your PRe
Because, all code already present in this repository

Also conflict the Code

2021-06-20 22:58 UTC, RAUNAK-PANDEY commented
@AkashSingh3031 Please check now

2021-06-21 03:53 UTC, AkashSingh3031 requested changes
Please, again check
Because in `Readme.md` file some author part is deleted & `important_book_link.md` file also some part delete

So, check this and resolve this issue

2021-06-21 12:04 UTC, AkashSingh3031 commented on 1]. DSA/450 DSA by ( Love Babbar Bhaiya )/C++/01]. Array/_07)_Cyclically_rotate_an_array_by_one.cpp
> +//Link : https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one2614/1
Accepted

2021-06-21 22:26 UTC, RAUNAK-PANDEY commented
@AkashSingh3031 Can you please check now. I have added deleted part and also it is showing no conflict with base branch.

2021-06-22 06:21 UTC, AkashSingh3031 commented on 1]. DSA/450 DSA by ( Love Babbar Bhaiya )/C++/01]. Array/_08)_Kadane's_Algorithm.cpp
> +//Link : https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1
This is question number 13
So write like `_13)_Kadane's_Algorithms.cpp`

And Put running & Accepted code on IDE

2021-06-22 06:22 UTC, AkashSingh3031 commented on 6]. Important Books/Important_Books_Link.md
>  |   |   ├── Python
REMOVE THIS also

2021-06-22 06:23 UTC, AkashSingh3031 requested changes
Please submit running & accepted code with correct numbering

2021-06-22 07:46 UTC, RAUNAK-PANDEY commented
@AkashSingh3031 Kadane's algorithm is repeated twice in that sheet at position 8 and 13  and all codes are executable. Please check

2021-06-22 08:12 UTC, AkashSingh3031 commented on 1]. DSA/450 DSA by ( Love Babbar Bhaiya )/C++/01]. Array/_08)_Kadane's_Algorithm.cpp
> +    int i,maxCur=arr[0];
![image](https://user-images.githubusercontent.com/60146338/122888440-80ba9f00-d35f-11eb-83f1-0a9bc1ad9509.png)


Running Code
![image](https://user-images.githubusercontent.com/60146338/122888660-ac3d8980-d35f-11eb-8863-4fb8cd129347.png)

2021-06-22 08:13 UTC, AkashSingh3031 commented on 1]. DSA/450 DSA by ( Love Babbar Bhaiya )/C++/01]. Array/_08)_Kadane's_Algorithm.cpp
> +
Rename with question number 8 or write 13

2021-06-22 08:15 UTC, AkashSingh3031 requested changes
Check question number 8

All code right only check again 8

Please update the readme of the book, don't delete something from there

2021-06-22 08:20 UTC, RAUNAK-PANDEY commented
@AkashSingh3031 my function name is :   int maxSubarraySum(int arr[], int n) but you have written int maxSubarraySum(int a[], int size) that is why it is showing error

2021-06-22 08:23 UTC, RAUNAK-PANDEY commented
And I have  updated readme.md file also.

2021-06-22 10:03 UTC, AkashSingh3031 commented on 1]. DSA/450 DSA by ( Love Babbar Bhaiya )/C++/01]. Array/_08)_Kadane's_Algorithm.cpp
> +#include<bits/stdc++.h>
Accepted

2021-06-22 10:11 UTC, AkashSingh3031 reviewed
Accepted

2021-06-22 10:11 UTC, merged